# -*- coding: utf-8 -*-
"""prompt_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oaJXyPb4niV1FGimAKmSWDQ1a30Nl3Vv
"""

#!pip install transformers requests
from transformers import pipeline
import pandas as pd

# Initialize a free text generation pipeline
generator = pipeline('text-generation', model='gpt2')  # Free small model

def get_completion(prompt, max_length=150):
    try:
        response = generator(prompt, max_length=max_length, do_sample=True)
        return response[0]['generated_text']
    except Exception as e:
        print(f"Error: {str(e)}")
        return None

# Our prompt pairs
prompt_pairs = [
    {"type": "descriptive", "prompt": "Tell me about social media's mental health impact"},
    {"type": "directive", "prompt": "List 5 negative effects of social media on teens"},
    {"type": "descriptive", "prompt": "Explain photosynthesis"},
    {"type": "directive", "prompt": "Describe light-dependent reactions in 3 steps"},
    {"type": "descriptive", "prompt": "Discuss Hamlet's themes"},
    {"type": "directive", "prompt": "Analyze revenge in Hamlet's Act 3 soliloquies"}
]

# Run experiments
results = []
for pair in prompt_pairs:
    response = get_completion(pair["prompt"])
    if response:
        results.append({
            "type": pair["type"],
            "prompt": pair["prompt"],
            "response": response.replace(pair["prompt"], '').strip(),
            "length": len(response.split())
        })

# Display results
if results:
    df = pd.DataFrame(results)
    print(df[['type', 'length', 'prompt']])

    # Comparison analysis
    for i in range(0, len(results)-1, 2):
        print(f"\nComparison {i//2 + 1}:")
        print(f"\nDescriptive ({results[i]['length']} words):")
        print(results[i]['response'][:300] + ("..." if len(results[i]['response']) > 300 else ""))
        print(f"\nDirective ({results[i+1]['length']} words):")
        print(results[i+1]['response'][:300] + ("..." if len(results[i+1]['response']) > 300 else ""))
else:
    print("No results generated. Please check your connection.")